#! /usr/bin/env bash
# source https://github.com/bettermarks/.github/git-hooks/
echo "executing $0 in $(pwd)"
set -eu
current_branch=$(git rev-parse --abbrev-ref HEAD)

# needs to be passed as the first argument, should be "main" or "master" in most cases
default_branch=$1

if [ ! -f ".git/refs/heads/$1" ]; then
  echo "There is no local branch with the name '$1', so it can not be the default branch."
  exit 2
fi

if [ "$current_branch" = "$default_branch" ]; then
  echo "Do not use the default branch '$default_branch' directly, create a feature branch!"
  exit 1
fi
