- id: no-commit-to-default-branch
  name: No commit to default branch
  entry: git-hooks/no-commit-to-default-branch
  always_run: true
  language: script
  pass_filenames: false
- id: pre-commit-autoupdate
  name: pre-commit autoupdate
  entry: pre-commit autoupdate
  language: system
  always_run: true
  pass_filenames: false
